### ISSUE TITLE
VDF module doesn't (de)serialize arrays as expected

### ISSUE THREAD

**Issue by rossengeorgiev** [Lagg/steamodd#40] opened 2015-07-07 08:44 UTC
``` python
>>> steam.__version__
'4.19'
>>> steam.vdf.dumps( {'a': [ 'b', [], {'c':5} ]} ).decode('utf-16')
"a"
{
  "b" "1"
  "[]" "1"
  "{'c': 5}" "1"
}
```

Expected:

``` python
"a"
{
  "0" "b"
  "1"
  {
  }
  "2"
  {
     "c" "5"
  }
}
```

It's not possible to get the original input, by passing it to `loads`

``` python
>>> steam.vdf.loads(steam.vdf.dumps({'a':[1,2,3]}))
{u'a': {u'1': u'1', u'2': u'1', u'3': u'1'}}
```

Root node can't be a `list`

``` python
>>> steam.vdf.dumps([1,2,3])
AttributeError: 'list' object has no attribute 'items'
```

**Comment by Lagg** [comment] 2015-07-08 02:19
Ouch, at least I know what the problem is though. vdf.py only treats dicts in a special way and I forgot to handle lists in the same manner. As for the non-dict root nodes, doesn't VDF require the root to be a normal KV node? What should the expected output of that look like?

**Comment by rossengeorgiev** [comment] 2015-07-08 02:34
Well. VDF is just KVs. I see no reason to not be able have `"0"` as the root node. I haven't seen a single file that does that. It's more of a consistency thing. The serialization part can easily be fixed.

```
if isinstance(value, list):
    value = enumerate(value)
```
I guess for deserialization you just check to see if the first subnode is `0` and turn into a `list`.
I've been thinking of adding that to my own `VDF` module. Essentially, deserialized data from the webapi will end up exactly the same, regardless of format being `json` or `vdf`. It makes sense.

**Comment by Lagg** [comment] 2015-07-08 21:07
I suppose, but we should consider whether or not there's actually a legit usecase where there is a "0" node that would cause problems when doing a `load`. I don't see any issues with making `dumps` wrap a 0 node around non-dict types though, it's better than outright failing right?

**Comment by rossengeorgiev** [comment] 2015-07-08 21:19
It shouldn't matter since the function is recursive. The only problem I found with proposed approach is that if you serialize `{1: []}` and then deserialize you get `{1: {}}` since detecting whenever the node is a list is done by checking if the first subnode `key == '0'`.

**Comment by Lagg** [comment] 2015-07-12 22:17
Sorry for late response. Alright then, I'll definitely make dumps work like expected but I'm still not 100% sure about considering any special cases for top level nodes in loads. At the very least it'd make it to where I had to do a major release of steamodd since that could potentially break things. I don't know, will think about it. Thanks for report.

**Comment by Lagg** [comment] 2023-01-27 07:19
Sorry if this pings OP but I have multiple issues around this timeframe that aren't closed/read for some reason. If I recall correctly I implemented the feature parity as discussed in the VDF stuff and then just didn't close this.

**Closed by Lagg** 2023-01-27 07:19 UTC
